import { ArtifactImage } from "@/components/ArtifactImage";
import { Eyebrow } from "@/components/Eyebrow";
import { Reveal } from "@/components/Reveal";

const chapters = [
  { n:"01", title:"DEFINE", state:"DRAFT → FUNDED", copy:"Commit the rule version, target amount, expiry, payment reference hash, ordered recipients and shares before the trust path begins.", meta:["Policy commitment","Recipient binding","Native C2FLR escrow"] },
  { n:"02", title:"PROVE", state:"PROOF_REQUESTED → PROOF_VERIFIED", copy:"A current Flare Data Connector attestation proves the referenced external transaction. The Core stores its digest and rejects replay.", meta:["EVMTransaction proof","Source transaction","On-chain verification"] },
  { n:"03", title:"COMPUTE", state:"COMPUTATION_REQUESTED", copy:"The registered FCC extension evaluates sealed commercial inputs and emits the minimum settlement result required by the contract.", meta:["Extension 66235","Private inputs sealed","Action reference bound"] },
  { n:"04", title:"SETTLE", state:"READY_TO_SETTLE → SETTLED", copy:"Core authenticates the EIP-191 result against the active TEE set, checks every binding, then releases the exact payout vector once.", meta:["TEE signer active","Nonce + expiry","Final receipt"] },
];

export default function HowItWorks() { return <main className="editorial-page"><section className="page-hero flagship-section"><Eyebrow>HOW IT WORKS</Eyebrow><h1>A trust path with<br /><em>no invisible leap.</em></h1><p className="lede">Four chapters connect policy intent, external evidence, private computation and final settlement.</p></section><section className="chapter-sequence">{chapters.map((chapter,index)=><Reveal key={chapter.n}><article className="chapter"><div className="chapter-number">{chapter.n}<span>/{chapters.length.toString().padStart(2,"0")}</span></div><div className="chapter-body"><p className="protocol-state">{chapter.state}</p><h2>{chapter.title}</h2><p>{chapter.copy}</p><ul>{chapter.meta.map(item=><li key={item}>{item}</li>)}</ul></div><div className={`chapter-art chapter-art-${index+1}`}>{index===1?<ArtifactImage src="/images/PROOF ARTIFACT.png" alt="External proof verification artifact" label="VERIFIED EVIDENCE" index="C/03" />:index===2?<ArtifactImage src="/images/PRIVATE COMPUTE ARTIFACT.png" alt="Private computation artifact" label="SEALED COMPUTATION" index="D/04" />:<div className="state-plane"><span>{chapter.state}</span><div>{chapter.meta.map((item,i)=><i key={item} style={{"--i":i} as React.CSSProperties}>{item}</i>)}</div></div>}</div></article></Reveal>)}</section></main>; }
